### ISSUE TITLE
Postgres database connection is not fully closed

### ISSUE THREAD

**Issue by madfist** [thenativeweb/wolkenkit#149]
### What is this bug about?

Calling `destroy()` on event store (postgres) leaves a connection open that leads to our application hanging

### What steps are needed to reproduce the bug?
```
const es = require('wolkenkit-eventstore/postgres')
const { Event } = require('commands-events')

require('wtfnode').init()

async function run() {
  await es.initialize({url: 'postgres://app:app@localhost/app', namespace: 'wolken'})
  const event = new Event({
    context: {
      name: 'network'
    },
    aggregate: {
      name: 'node',
      id: '85932442-bf87-472d-8b5a-b0eac3aa8be9'
    },
    name: 'pinged',
    metadata: {
      correlationId: '13505cab-0ca2-4502-b8c9-8f3ce63ae390',
      causationId: '124885f3-d35e-43a6-84eb-e28c70b5be66',
    }
  })
  event.metadata.revision = 1
  await es.saveEvents({events: [event]})
  await es.destroy()
}

run()
```
### What is the expected result?
Script exits on its own

### What is the actual result?
Need close it with CTRL+C. `wtfnode` shows that a connection is still active:
```
^C[WTF Node?] open handles:
- Sockets:
  - 127.0.0.1:54142 -> 127.0.0.1:5432
    - Listeners:
      - connect: Connection.connect @ .../project/node_modules/pg/lib/connection.js:58
```

### What else should we know?
It is probably the `disconnectWatcher` connection. Other databases not checked
